blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: https://github.com/woheedev/bptimer/security/advisories/new
    about: Please report security vulnerabilities here.
  - name: General Discussion
    url: https://github.com/woheedev/bptimer/discussions
    about: For general questions and discussions about the project.
